-- Schema for Supabase (public)
-- Apply in Supabase SQL editor.

-- Extensions
create extension if not exists "pgcrypto";

-- Enums
do $$ begin
  create type public.user_role as enum ('admin','user');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.payment_method as enum ('cod','bank_transfer');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.payment_status as enum ('unpaid','pending_confirmation','paid','refunded');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.order_status as enum ('pending','confirmed','processing','shipping','delivered','cancelled');
exception when duplicate_object then null; end $$;

-- Profiles (app user data)
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  legacy_user_id integer unique,
  username text unique,
  student_code text unique,
  full_name text not null,
  email text unique,
  phone_number text unique,
  role public.user_role not null default 'user',
  is_active boolean not null default true,
  total_fine numeric(18,2) not null default 0,
  paid_amount numeric(18,2) not null default 0,
  customer_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists profiles_role_idx on public.profiles(role);

-- Categories
create table if not exists public.categories (
  category_id text primary key,
  name text not null,
  description text,
  created_at timestamptz not null default now()
);

-- Books
create table if not exists public.books (
  book_id text primary key,
  title text not null,
  author text not null,
  publisher text,
  isbn text,
  category_id text not null references public.categories(category_id),
  price numeric(18,2) not null default 0,
  sale_price numeric(18,2),
  description text,
  slug text,
  is_published boolean not null default true,
  publish_year integer not null,
  quantity integer not null default 0,
  location text,
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists books_category_idx on public.books(category_id);
create index if not exists books_published_idx on public.books(is_published);

-- Settings (key/value)
create table if not exists public.settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

-- Orders
create table if not exists public.orders (
  order_id bigint generated by default as identity primary key,
  legacy_order_id integer unique,
  user_id uuid not null references auth.users(id),
  order_code text not null unique,
  status public.order_status not null default 'pending',
  payment_method public.payment_method not null default 'cod',
  payment_status public.payment_status not null default 'unpaid',
  receiver_name text not null,
  receiver_phone text not null,
  shipping_address text not null,
  note text,
  subtotal numeric(18,2) not null default 0,
  shipping_fee numeric(18,2) not null default 0,
  discount numeric(18,2) not null default 0,
  total numeric(18,2) not null default 0,
  bank_transfer_reference text,
  created_at timestamptz not null default now(),
  confirmed_at timestamptz,
  delivered_at timestamptz,
  cancelled_at timestamptz
);

create index if not exists orders_user_idx on public.orders(user_id);
create index if not exists orders_created_idx on public.orders(created_at desc);

-- Order items
create table if not exists public.order_items (
  order_item_id bigint generated by default as identity primary key,
  legacy_order_item_id integer unique,
  order_id bigint not null references public.orders(order_id) on delete cascade,
  book_id text not null references public.books(book_id),
  unit_price numeric(18,2) not null,
  quantity integer not null check (quantity >= 1 and quantity <= 999),
  line_total numeric(18,2) not null
);

create index if not exists order_items_order_idx on public.order_items(order_id);
create index if not exists order_items_book_idx on public.order_items(book_id);

-- Notifications
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  legacy_notification_id integer unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null,
  title text not null,
  message text not null,
  link text,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  related_entity_id bigint
);

create index if not exists notifications_user_idx on public.notifications(user_id);

-- UpdatedAt trigger helper
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$ begin
  create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute procedure public.set_updated_at();
exception when duplicate_object then null; end $$;

do $$ begin
  create trigger books_set_updated_at
  before update on public.books
  for each row execute procedure public.set_updated_at();
exception when duplicate_object then null; end $$;

