-- Extensions
create extension if not exists "pgcrypto";

-- Enums
do $$ begin
  create type public.user_role as enum ('admin','user');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.payment_method as enum ('cod','bank_transfer');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.payment_status as enum ('unpaid','pending_confirmation','paid','partially_refunded','refunded');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.order_status as enum ('pending','confirmed','processing','shipping','delivered','cancelled', 'returned');
exception when duplicate_object then null; end $$;

-- Profiles (Tối ưu cho khách hàng mua sắm)
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  full_name text not null,
  email text unique,
  phone_number text unique,
  avatar_url text,
  default_address text,
  role public.user_role not null default 'user',
  is_active boolean not null default true,
  loyalty_points integer not null default 0,
  customer_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists profiles_role_idx on public.profiles(role);

-- Categories
create table if not exists public.categories (
  category_id text primary key,
  name text not null,
  description text,
  created_at timestamptz not null default now()
);

-- Books (Thêm ràng buộc E-commerce)
create table if not exists public.books (
  book_id text primary key,
  title text not null,
  author text not null,
  publisher text,
  isbn text,
  category_id text not null references public.categories(category_id),
  price numeric(18,2) not null default 0 check (price >= 0),
  sale_price numeric(18,2) check (sale_price <= price),
  is_on_sale boolean default false,
  description text,
  slug text unique not null,
  is_published boolean not null default true,
  publish_year integer not null,
  quantity integer not null default 0 check (quantity >= 0),
  location text,
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists books_category_idx on public.books(category_id);
create index if not exists books_published_idx on public.books(is_published);
create index if not exists books_sale_idx on public.books(sale_price) where sale_price is not null;

-- Vouchers (Bảng mới quản lý khuyến mãi)
create table if not exists public.vouchers (
  code text primary key,
  discount_percent integer check (discount_percent > 0 and discount_percent <= 100),
  max_discount_amount numeric(18,2),
  valid_until timestamptz,
  is_active boolean default true
);

-- Settings
create table if not exists public.settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

-- Orders
create table if not exists public.orders (
  order_id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id),
  order_code text not null unique,
  status public.order_status not null default 'pending',
  payment_method public.payment_method not null default 'cod',
  payment_status public.payment_status not null default 'unpaid',
  receiver_name text not null,
  receiver_phone text not null,
  shipping_address text not null,
  note text,
  subtotal numeric(18,2) not null default 0,
  shipping_fee numeric(18,2) not null default 0,
  discount numeric(18,2) not null default 0,
  total numeric(18,2) not null default 0,
  bank_transfer_reference text,
  created_at timestamptz not null default now(),
  confirmed_at timestamptz,
  delivered_at timestamptz,
  cancelled_at timestamptz
);

create index if not exists orders_user_idx on public.orders(user_id);
create index if not exists orders_created_idx on public.orders(created_at desc);

-- Order items
create table if not exists public.order_items (
  order_item_id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(order_id) on delete cascade,
  book_id text not null references public.books(book_id),
  unit_price numeric(18,2) not null,
  quantity integer not null check (quantity >= 1 and quantity <= 999),
  line_total numeric(18,2) not null
);

create index if not exists order_items_order_idx on public.order_items(order_id);
create index if not exists order_items_book_idx on public.order_items(book_id);

-- Cart Items (Giỏ hàng)
create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  book_id text not null references public.books(book_id) on delete cascade,
  quantity integer not null default 1 check (quantity >= 1 and quantity <= 999),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, book_id)
);

-- Tạo Index để tối ưu tốc độ truy vấn giỏ hàng của một user
create index if not exists cart_items_user_idx on public.cart_items(user_id);

-- Thêm Trigger tự động cập nhật updated_at (tận dụng hàm set_updated_at đã có của bạn)
do $$ begin
  create trigger cart_items_set_updated_at
  before update on public.cart_items
  for each row execute procedure public.set_updated_at();
exception when duplicate_object then null; end $$;

-- Notifications
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null,
  title text not null,
  message text not null,
  link text,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  related_entity_id bigint
);

create index if not exists notifications_user_idx on public.notifications(user_id);

create table if not exists public.admin_notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  type text not null default 'system',
  link text,
  recipients_type text not null default 'all',
  recipient_ids jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- UpdatedAt trigger helper
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$ begin
  create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute procedure public.set_updated_at();
exception when duplicate_object then null; end $$;

do $$ begin
  create trigger books_set_updated_at
  before update on public.books
  for each row execute procedure public.set_updated_at();
exception when duplicate_object then null; end $$;

create extension if not exists pg_cron;

select cron.schedule(
  'deactivate-expired-vouchers',
  '* * * * *',
  $$ 
    update public.vouchers 
    set is_active = false 
    where is_active = true 
      and valid_until < now() 
  $$
);
